// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: garnet_event.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_garnet_5fevent_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_garnet_5fevent_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_garnet_5fevent_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_garnet_5fevent_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_garnet_5fevent_2eproto;
namespace garnetlog {
class GarnetEvent;
class GarnetEventDefaultTypeInternal;
extern GarnetEventDefaultTypeInternal _GarnetEvent_default_instance_;
}  // namespace garnetlog
PROTOBUF_NAMESPACE_OPEN
template<> ::garnetlog::GarnetEvent* Arena::CreateMaybeMessage<::garnetlog::GarnetEvent>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace garnetlog {

// ===================================================================

class GarnetEvent PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:garnetlog.GarnetEvent) */ {
 public:
  inline GarnetEvent() : GarnetEvent(nullptr) {};
  virtual ~GarnetEvent();

  GarnetEvent(const GarnetEvent& from);
  GarnetEvent(GarnetEvent&& from) noexcept
    : GarnetEvent() {
    *this = ::std::move(from);
  }

  inline GarnetEvent& operator=(const GarnetEvent& from) {
    CopyFrom(from);
    return *this;
  }
  inline GarnetEvent& operator=(GarnetEvent&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GarnetEvent& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GarnetEvent* internal_default_instance() {
    return reinterpret_cast<const GarnetEvent*>(
               &_GarnetEvent_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(GarnetEvent& a, GarnetEvent& b) {
    a.Swap(&b);
  }
  inline void Swap(GarnetEvent* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GarnetEvent* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GarnetEvent* New() const final {
    return CreateMaybeMessage<GarnetEvent>(nullptr);
  }

  GarnetEvent* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GarnetEvent>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GarnetEvent& from);
  void MergeFrom(const GarnetEvent& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GarnetEvent* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "garnetlog.GarnetEvent";
  }
  protected:
  explicit GarnetEvent(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_garnet_5fevent_2eproto);
    return ::descriptor_table_garnet_5fevent_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStatusFieldNumber = 2,
    kTickFieldNumber = 1,
    kGlobalIdFieldNumber = 3,
    kPacketIdFieldNumber = 4,
    kIdFieldNumber = 5,
    kLinkIdFieldNumber = 6,
    kSrcFieldNumber = 7,
    kDestFieldNumber = 8,
  };
  // string status = 2;
  void clear_status();
  const std::string& status() const;
  void set_status(const std::string& value);
  void set_status(std::string&& value);
  void set_status(const char* value);
  void set_status(const char* value, size_t size);
  std::string* mutable_status();
  std::string* release_status();
  void set_allocated_status(std::string* status);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_status();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_status(
      std::string* status);
  private:
  const std::string& _internal_status() const;
  void _internal_set_status(const std::string& value);
  std::string* _internal_mutable_status();
  public:

  // int64 tick = 1;
  void clear_tick();
  ::PROTOBUF_NAMESPACE_ID::int64 tick() const;
  void set_tick(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_tick() const;
  void _internal_set_tick(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // uint64 global_id = 3;
  void clear_global_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 global_id() const;
  void set_global_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_global_id() const;
  void _internal_set_global_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 packet_id = 4;
  void clear_packet_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 packet_id() const;
  void set_packet_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_packet_id() const;
  void _internal_set_packet_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 id = 5;
  void clear_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 id() const;
  void set_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_id() const;
  void _internal_set_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 link_id = 6;
  void clear_link_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 link_id() const;
  void set_link_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_link_id() const;
  void _internal_set_link_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 src = 7;
  void clear_src();
  ::PROTOBUF_NAMESPACE_ID::uint64 src() const;
  void set_src(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_src() const;
  void _internal_set_src(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 dest = 8;
  void clear_dest();
  ::PROTOBUF_NAMESPACE_ID::uint64 dest() const;
  void set_dest(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_dest() const;
  void _internal_set_dest(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:garnetlog.GarnetEvent)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr status_;
  ::PROTOBUF_NAMESPACE_ID::int64 tick_;
  ::PROTOBUF_NAMESPACE_ID::uint64 global_id_;
  ::PROTOBUF_NAMESPACE_ID::uint64 packet_id_;
  ::PROTOBUF_NAMESPACE_ID::uint64 id_;
  ::PROTOBUF_NAMESPACE_ID::uint64 link_id_;
  ::PROTOBUF_NAMESPACE_ID::uint64 src_;
  ::PROTOBUF_NAMESPACE_ID::uint64 dest_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_garnet_5fevent_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GarnetEvent

// int64 tick = 1;
inline void GarnetEvent::clear_tick() {
  tick_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 GarnetEvent::_internal_tick() const {
  return tick_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 GarnetEvent::tick() const {
  // @@protoc_insertion_point(field_get:garnetlog.GarnetEvent.tick)
  return _internal_tick();
}
inline void GarnetEvent::_internal_set_tick(::PROTOBUF_NAMESPACE_ID::int64 value) {

  tick_ = value;
}
inline void GarnetEvent::set_tick(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_tick(value);
  // @@protoc_insertion_point(field_set:garnetlog.GarnetEvent.tick)
}

// string status = 2;
inline void GarnetEvent::clear_status() {
  status_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& GarnetEvent::status() const {
  // @@protoc_insertion_point(field_get:garnetlog.GarnetEvent.status)
  return _internal_status();
}
inline void GarnetEvent::set_status(const std::string& value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:garnetlog.GarnetEvent.status)
}
inline std::string* GarnetEvent::mutable_status() {
  // @@protoc_insertion_point(field_mutable:garnetlog.GarnetEvent.status)
  return _internal_mutable_status();
}
inline const std::string& GarnetEvent::_internal_status() const {
  return status_.Get();
}
inline void GarnetEvent::_internal_set_status(const std::string& value) {

  status_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void GarnetEvent::set_status(std::string&& value) {

  status_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:garnetlog.GarnetEvent.status)
}
inline void GarnetEvent::set_status(const char* value) {
  GOOGLE_DCHECK(value != nullptr);

  status_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:garnetlog.GarnetEvent.status)
}
inline void GarnetEvent::set_status(const char* value,
    size_t size) {

  status_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:garnetlog.GarnetEvent.status)
}
inline std::string* GarnetEvent::_internal_mutable_status() {

  return status_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* GarnetEvent::release_status() {
  // @@protoc_insertion_point(field_release:garnetlog.GarnetEvent.status)
  return status_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void GarnetEvent::set_allocated_status(std::string* status) {
  if (status != nullptr) {

  } else {

  }
  status_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), status,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:garnetlog.GarnetEvent.status)
}
inline std::string* GarnetEvent::unsafe_arena_release_status() {
  // @@protoc_insertion_point(field_unsafe_arena_release:garnetlog.GarnetEvent.status)
  GOOGLE_DCHECK(GetArena() != nullptr);

  return status_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void GarnetEvent::unsafe_arena_set_allocated_status(
    std::string* status) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (status != nullptr) {

  } else {

  }
  status_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      status, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:garnetlog.GarnetEvent.status)
}

// uint64 global_id = 3;
inline void GarnetEvent::clear_global_id() {
  global_id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 GarnetEvent::_internal_global_id() const {
  return global_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 GarnetEvent::global_id() const {
  // @@protoc_insertion_point(field_get:garnetlog.GarnetEvent.global_id)
  return _internal_global_id();
}
inline void GarnetEvent::_internal_set_global_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {

  global_id_ = value;
}
inline void GarnetEvent::set_global_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_global_id(value);
  // @@protoc_insertion_point(field_set:garnetlog.GarnetEvent.global_id)
}

// uint64 packet_id = 4;
inline void GarnetEvent::clear_packet_id() {
  packet_id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 GarnetEvent::_internal_packet_id() const {
  return packet_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 GarnetEvent::packet_id() const {
  // @@protoc_insertion_point(field_get:garnetlog.GarnetEvent.packet_id)
  return _internal_packet_id();
}
inline void GarnetEvent::_internal_set_packet_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {

  packet_id_ = value;
}
inline void GarnetEvent::set_packet_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_packet_id(value);
  // @@protoc_insertion_point(field_set:garnetlog.GarnetEvent.packet_id)
}

// uint64 id = 5;
inline void GarnetEvent::clear_id() {
  id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 GarnetEvent::_internal_id() const {
  return id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 GarnetEvent::id() const {
  // @@protoc_insertion_point(field_get:garnetlog.GarnetEvent.id)
  return _internal_id();
}
inline void GarnetEvent::_internal_set_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {

  id_ = value;
}
inline void GarnetEvent::set_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:garnetlog.GarnetEvent.id)
}

// uint64 link_id = 6;
inline void GarnetEvent::clear_link_id() {
  link_id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 GarnetEvent::_internal_link_id() const {
  return link_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 GarnetEvent::link_id() const {
  // @@protoc_insertion_point(field_get:garnetlog.GarnetEvent.link_id)
  return _internal_link_id();
}
inline void GarnetEvent::_internal_set_link_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {

  link_id_ = value;
}
inline void GarnetEvent::set_link_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_link_id(value);
  // @@protoc_insertion_point(field_set:garnetlog.GarnetEvent.link_id)
}

// uint64 src = 7;
inline void GarnetEvent::clear_src() {
  src_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 GarnetEvent::_internal_src() const {
  return src_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 GarnetEvent::src() const {
  // @@protoc_insertion_point(field_get:garnetlog.GarnetEvent.src)
  return _internal_src();
}
inline void GarnetEvent::_internal_set_src(::PROTOBUF_NAMESPACE_ID::uint64 value) {

  src_ = value;
}
inline void GarnetEvent::set_src(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_src(value);
  // @@protoc_insertion_point(field_set:garnetlog.GarnetEvent.src)
}

// uint64 dest = 8;
inline void GarnetEvent::clear_dest() {
  dest_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 GarnetEvent::_internal_dest() const {
  return dest_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 GarnetEvent::dest() const {
  // @@protoc_insertion_point(field_get:garnetlog.GarnetEvent.dest)
  return _internal_dest();
}
inline void GarnetEvent::_internal_set_dest(::PROTOBUF_NAMESPACE_ID::uint64 value) {

  dest_ = value;
}
inline void GarnetEvent::set_dest(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_dest(value);
  // @@protoc_insertion_point(field_set:garnetlog.GarnetEvent.dest)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace garnetlog

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_garnet_5fevent_2eproto
